export const HIGH_SCHOOL_SUBJECTS = [
  { name: "Mathematics", emoji: "🧮" },
  { name: "Physics", emoji: "⚛️" },
  { name: "Chemistry", emoji: "🧪" },
  { name: "Biology", emoji: "🔬" },
  { name: "English", emoji: "📖" },
  { name: "Literature", emoji: "✍️" },
  { name: "History", emoji: "🏛️" },
  { name: "Geography", emoji: "🌍" },
  { name: "Computer Science", emoji: "💻" },
  { name: "Programming", emoji: "👨‍💻" },
  { name: "Art", emoji: "🎨" },
  { name: "Music", emoji: "🎵" },
  { name: "Physical Education (PE)", emoji: "⚽" },
  { name: "Health Education", emoji: "🏥" },
  { name: "Economics", emoji: "💹" },
  { name: "Business Studies", emoji: "📊" },
  { name: "Psychology", emoji: "🧠" },
  { name: "Sociology", emoji: "👥" },
  { name: "Political Science", emoji: "🏛️" },
  { name: "Philosophy", emoji: "🤔" },
  { name: "Foreign Languages", emoji: "🗣️" },
  { name: "Spanish", emoji: "🇪🇸" },
  { name: "French", emoji: "🇫🇷" },
  { name: "German", emoji: "🇩🇪" },
  { name: "Chinese", emoji: "🇨🇳" },
  { name: "Latin", emoji: "🏺" },
  { name: "Religious Studies", emoji: "🕍" },
  { name: "Environmental Science", emoji: "🌱" },
  { name: "Engineering", emoji: "⚙️" },
  { name: "Drama", emoji: "🎭" },
  { name: "Dance", emoji: "💃" },
  { name: "Home Economics", emoji: "🍳" },
  { name: "Agriculture", emoji: "🚜" },
  { name: "Astronomy", emoji: "🔭" },
  { name: "Statistics", emoji: "📈" },
  { name: "Media Studies", emoji: "🎥" },
  { name: "Journalism", emoji: "📰" },
  { name: "Robotics", emoji: "🤖" },
  { name: "Graphic Design", emoji: "🎨" },
  { name: "Culinary Arts", emoji: "👨‍🍳" },
  { name: "Woodworking", emoji: "🪵" },
  { name: "Automotive", emoji: "🚗" },
]

export const UNIVERSITY_SUBJECTS = [
  // Sciences & Engineering
  { name: "Advanced Mathematics", emoji: "🧮" },
  { name: "Quantum Physics", emoji: "⚛️" },
  { name: "Organic Chemistry", emoji: "🔬" },
  { name: "Astrophysics", emoji: "🌌" },
  { name: "Biomedical Engineering", emoji: "🦾" },
  { name: "Nanotechnology", emoji: "🔍" },
  { name: "Artificial Intelligence", emoji: "🧠" },
  { name: "Machine Learning", emoji: "🤖" },
  { name: "Aerospace Engineering", emoji: "✈️" },
  { name: "Robotics", emoji: "🦿" },
  { name: "Civil Engineering", emoji: "🏗️" },
  { name: "Electrical Engineering", emoji: "⚡" },
  { name: "Computer Science", emoji: "💻" },
  { name: "Cybersecurity", emoji: "🔒" },
  { name: "Data Science", emoji: "📊" },
  { name: "Environmental Engineering", emoji: "🌿" },

  // Medicine & Life Sciences
  { name: "Medicine (MBBS)", emoji: "⚕️" },
  { name: "Neuroscience", emoji: "🧠" },
  { name: "Genetics", emoji: "🧬" },
  { name: "Pharmacology", emoji: "💊" },
  { name: "Virology", emoji: "🦠" },
  { name: "Public Health", emoji: "🏥" },
  { name: "Dentistry", emoji: "🦷" },
  { name: "Veterinary Science", emoji: "🐾" },

  // Humanities & Social Sciences
  { name: "Philosophy", emoji: "🤔" },
  { name: "Political Science", emoji: "🏛️" },
  { name: "International Relations", emoji: "🌐" },
  { name: "Psychology", emoji: "🧠" },
  { name: "Sociology", emoji: "👥" },
  { name: "Anthropology", emoji: "🦴" },
  { name: "Archaeology", emoji: "⛏️" },
  { name: "Linguistics", emoji: "🗣️" },
  { name: "Classical Studies", emoji: "🏺" },
  { name: "Theology", emoji: "⛪" },
  { name: "Gender Studies", emoji: "⚧️" },

  // Business & Economics
  { name: "Economics", emoji: "💹" },
  { name: "Finance", emoji: "💰" },
  { name: "Business Administration", emoji: "📈" },
  { name: "Marketing", emoji: "📢" },
  { name: "Entrepreneurship", emoji: "🚀" },
  { name: "Accounting", emoji: "🧮" },
  { name: "Supply Chain Management", emoji: "📦" },
  { name: "International Business", emoji: "🌍" },

  // Arts & Design
  { name: "Fine Arts", emoji: "🎨" },
  { name: "Graphic Design", emoji: "✏️" },
  { name: "Film Studies", emoji: "🎥" },
  { name: "Music Theory", emoji: "🎼" },
  { name: "Architecture", emoji: "🏛️" },
  { name: "Fashion Design", emoji: "👗" },
  { name: "Creative Writing", emoji: "✍️" },
  { name: "Theatre & Drama", emoji: "🎭" },

  // Law & Criminal Justice
  { name: "Law (LLB/JD)", emoji: "⚖️" },
  { name: "Criminology", emoji: "🕵️" },
  { name: "Forensic Science", emoji: "🔎" },
  { name: "Human Rights Law", emoji: "✊" },

  // Technology & Emerging Fields
  { name: "Blockchain Technology", emoji: "⛓️" },
  { name: "Virtual Reality (VR)", emoji: "👓" },
  { name: "Ethical Hacking", emoji: "👨‍💻" },
  { name: "Renewable Energy", emoji: "☀️" },
  { name: "Bioinformatics", emoji: "🧬💻" },

  // Interdisciplinary Studies
  { name: "Cognitive Science", emoji: "🧠🔍" },
  { name: "Environmental Policy", emoji: "🌱📜" },
  { name: "Digital Humanities", emoji: "💻📚" },
]
